# Generated by Django 6.0.6 on 2026-06-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_testimonial_created_at_testimonial_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='BikeMart', max_length=150)),
                ('owner_name', models.CharField(default='Mr. Mari Vigneshwaran', max_length=150)),
                ('address', models.TextField(default='Chennai, Tamil Nadu')),
                ('phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('email', models.EmailField(default='bikemart@example.com', max_length=254)),
                ('working_hours', models.CharField(default='9:00 AM - 8:00 PM', max_length=100)),
                ('map_location', models.CharField(default='Chennai Tamil Nadu', help_text='Enter Google map search location. Example: Tambaram Chennai Tamil Nadu', max_length=255)),
                ('short_description', models.TextField(default='Trusted second-hand bike showroom for verified bikes, fair pricing, and easy customer support.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop Setting',
                'verbose_name_plural': 'Shop Settings',
            },
        ),
    ]
