# Generated by Django 6.0.6 on 2026-06-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_shopsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('id_proof_file', models.FileField(blank=True, null=True, upload_to='employee_id_proofs/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='id_proof_file',
            field=models.FileField(blank=True, null=True, upload_to='customer_id_proofs/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='customer_photos/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='id_proof_file',
            field=models.FileField(blank=True, null=True, upload_to='vendor_id_proofs/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_photos/'),
        ),
    ]
