# Generated by Django 6.0.6 on 2026-06-17 09:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_employee_customer_id_proof_file_customer_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('bill_date', models.DateField(default=django.utils.timezone.now)),
                ('bike_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('settlement_type', models.CharField(choices=[('full', 'Full Settlement'), ('finance', 'Finance')], default='full', max_length=20)),
                ('finance_company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('finance_down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('finance_interest_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('finance_months', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_emi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI')], default='cash', max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bikes.bike')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bikes.customer')),
            ],
        ),
    ]
