# Generated by Django 6.0.6 on 2026-06-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_billpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='finance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='finance_interest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final price minus advance amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='total_amount_include_interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
