# Generated by Django 6.0.6 on 2026-06-18 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0006_billpayment_finance_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bike_photos/')),
                ('caption', models.CharField(blank=True, max_length=150, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bikes.bike')),
            ],
        ),
    ]
