# Generated by Django 6.0.6 on 2026-06-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0008_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpayment',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid by customer', max_digits=10),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Balance amount after paid amount', max_digits=10),
        ),
    ]
