# Generated by Django 6.0.6 on 2026-06-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0010_auditlog_ip_address_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='category',
            field=models.CharField(choices=[('bike', 'Bike'), ('scooter', 'Scooter'), ('ev', 'EV')], default='bike', max_length=20),
        ),
    ]
