# Generated by Django 6.0.6 on 2026-06-26 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0011_bike_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id_proof_file',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id_proof_file',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='id_proof_file',
        ),
        migrations.CreateModel(
            name='CustomerIdProofFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='customer_id_proofs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_proof_files', to='bikes.customer')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeIdProofFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='employee_id_proofs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_proof_files', to='bikes.employee')),
            ],
        ),
        migrations.CreateModel(
            name='VendorIdProofFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vendor_id_proofs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_proof_files', to='bikes.vendor')),
            ],
        ),
    ]
